from pathlib import Path


def ensure_directory(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    print(f"[OK] Folder ready: {path}")


def ensure_file(path: Path, content: str = "") -> None:
    if not path.exists():
        path.write_text(content, encoding="utf-8")
        print(f"[OK] File created: {path}")
    else:
        print(f"[SKIP] File already exists: {path}")


def main() -> None:
    base_path = Path.cwd()

    folders = ["Source", "Output", "Program"]
    for folder in folders:
        ensure_directory(base_path / folder)

    ensure_file(base_path / "README.txt", "Project setup generated by initilization.py\n")

    bat_content = "@echo off\npython First.py\npause\n"
    ensure_file(base_path / "Run Program.bat", bat_content)

    print("\nSetup completed.")


if __name__ == "__main__":
    main()
