from pathlib import Path
from urllib.error import URLError, HTTPError
from urllib.request import urlopen
import shutil

INITIALIZATION_VERSION = "0.1"
PROGRAM_DOWNLOADS = {
    "check_source_and_extract_to_output.py": "https://raw.githubusercontent.com/FireDragonSlayer/FireDragon-TOM-Modfix/main/programs/check_source_and_extract_to_output.py",
    "rename_duplicate_mod_folders.py": "https://raw.githubusercontent.com/FireDragonSlayer/FireDragon-TOM-Modfix/main/programs/rename_duplicate_mod_folders.py",
    "validate_output_structure.py": "https://raw.githubusercontent.com/FireDragonSlayer/FireDragon-TOM-Modfix/main/programs/validate_output_structure.py",
}


def ensure_directory(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    print(f"[OK] Folder ready: {path}")


def ensure_file(path: Path, content: str = "") -> None:
    if not path.exists():
        path.write_text(content, encoding="utf-8")
        print(f"[OK] File created: {path}")
    else:
        print(f"[SKIP] File already exists: {path}")


def download_program(programs_path: Path, filename: str, url: str) -> None:
    target_path = programs_path / filename
    try:
        with urlopen(url, timeout=30) as response:
            content = response.read().decode("utf-8")
        target_path.write_text(content, encoding="utf-8")
        print(f"[OK] Downloaded: {filename}")
    except (HTTPError, URLError, TimeoutError) as error:
        local_source = Path(__file__).resolve().parent / "programs" / filename
        if local_source.exists():
            shutil.copy2(local_source, target_path)
            print(f"[OK] Download blocked, copied bundled file instead: {filename}")
        else:
            print(f"[WARN] Failed to download {filename}: {error}")


def main() -> None:
    base_path = Path.cwd()

    folders = ["Source", "Output", "programs"]
    for folder in folders:
        ensure_directory(base_path / folder)

    ensure_file(
        base_path / "README.txt",
        "Project setup generated by initilization.py\n"
        f"Release version: v{INITIALIZATION_VERSION}\n",
    )

    bat_content = "@echo off\npython First.py\npause\n"
    ensure_file(base_path / "Run Program.bat", bat_content)

    programs_path = base_path / "programs"
    for filename, url in PROGRAM_DOWNLOADS.items():
        download_program(programs_path, filename, url)

    print(f"\nSetup completed (v{INITIALIZATION_VERSION}).")


if __name__ == "__main__":
    main()
